# Values used for the deployed application.
replicaCount: 2
service:
  name: locations-smartlogic-notifier
config:
  smartlogicModelKey: "smartlogic.locations.model"
  logLevel: INFO
  kafkaTopic: SmartlogicConcept
  conceptUriPrefix: "http://www.ft.com/ontology/managedlocation/"