# Values used for the deployed application.
replicaCount: 2
service:
  name: smartlogic-notifier
config:
  smartlogicModel: "smartlogic.model"
  logLevel: INFO
  kafkaTopic: SmartlogicConcept
  conceptUriPrefix: "http://www.ft.com/thing/"