# Default values for smartlogic-notifier.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
service:
  name: "" # The name of the service, should be defined in the specific app-configs folder.
  hasHealthcheck: "true"
replicaCount: 1
image:
  repository: coco/smartlogic-notifier
  pullPolicy: IfNotPresent
resources:
  requests:
    memory: 32Mi
  limits:
    memory: 128Mi


